#!/usr/bin/env bash
set -euo pipefail

APP_USER="${APP_USER:-openfang}"
APP_GROUP="${APP_GROUP:-openfang}"
OPENFANG_HOME="${OPENFANG_HOME:-/data}"
CONFIG_PATH="${OPENFANG_HOME}/config.toml"
USER_CONFIG_PATH="${OPENFANG_HOME}/config.user.toml"
SECRETS_PATH="${OPENFANG_HOME}/secrets.env"

PORT="${PORT:-8080}"
SETUP_PASSWORD="${SETUP_PASSWORD:-}"
OPENFANG_API_KEY="${OPENFANG_API_KEY:-}"
OPENFANG_DEFAULT_PROVIDER="${OPENFANG_DEFAULT_PROVIDER:-anthropic}"
OPENFANG_DEFAULT_MODEL="${OPENFANG_DEFAULT_MODEL:-claude-sonnet-4-20250514}"
OPENFANG_DEFAULT_API_KEY_ENV="${OPENFANG_DEFAULT_API_KEY_ENV:-ANTHROPIC_API_KEY}"
OPENFANG_LOG_LEVEL="${OPENFANG_LOG_LEVEL:-info}"
OPENFANG_MEMORY_DECAY_RATE="${OPENFANG_MEMORY_DECAY_RATE:-0.05}"
OPENFANG_ENABLE_NETWORK="${OPENFANG_ENABLE_NETWORK:-false}"

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

normalize_bool() {
  case "${1,,}" in
    1|true|yes|on) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

mkdir -p "${OPENFANG_HOME}"
touch "${SECRETS_PATH}"

chown -R "${APP_USER}:${APP_GROUP}" "${OPENFANG_HOME}"
chmod 700 "${OPENFANG_HOME}"
chmod 600 "${SECRETS_PATH}"

cat > "${CONFIG_PATH}" <<EOF
# Generated by entrypoint.sh on every boot.
# Put advanced overrides in config.user.toml so they survive template updates.
include = ["config.user.toml"]

home_dir = "$(toml_escape "${OPENFANG_HOME}")"
data_dir = "$(toml_escape "${OPENFANG_HOME}/data")"
log_level = "$(toml_escape "${OPENFANG_LOG_LEVEL}")"
api_listen = "127.0.0.1:4200"
api_key = "$(toml_escape "${OPENFANG_API_KEY}")"
network_enabled = $(normalize_bool "${OPENFANG_ENABLE_NETWORK}")

[default_model]
provider = "$(toml_escape "${OPENFANG_DEFAULT_PROVIDER}")"
model = "$(toml_escape "${OPENFANG_DEFAULT_MODEL}")"
api_key_env = "$(toml_escape "${OPENFANG_DEFAULT_API_KEY_ENV}")"

[memory]
decay_rate = ${OPENFANG_MEMORY_DECAY_RATE}
EOF

if [ ! -f "${USER_CONFIG_PATH}" ]; then
  cat > "${USER_CONFIG_PATH}" <<'EOF'
# This file is included by config.toml on every boot.
# Add any valid OpenFang configuration here:
# https://www.openfang.sh/docs/configuration
#
# Examples:
#
# [web]
# search_provider = "duck_duck_go"
#
# [[mcp_servers]]
# name = "filesystem"
# timeout_secs = 30
# [mcp_servers.transport]
# type = "stdio"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
EOF
fi

chmod 600 "${CONFIG_PATH}" "${USER_CONFIG_PATH}"

exec gosu "${APP_USER}:${APP_GROUP}" node src/server.js
